[app]
name = "browser"
package_domain = "com.example"
version = "0.1"
main_file = "main.py"
target_platforms = ["android"]
dependency_mapping = "dependency_mappings"

[app.dependency]
runtime_packages = ["kivy==2.3.1", "pyjnius"]
buildtime_packages = ["sdl2==2.32.2", "sdl2_ttf==2.24.0", "sdl2_mixer==2.8.1", "sdl2_image==2.8.8", "libffi==3.5.2", "openssl==3.6.0"]



[android]
cmdline_tools_version = "13114758"
sdk_version = "36"
ndk_version = "28.2.13676358"
min_sdk_version = "24"
ndk_api = "24"
archs = ["arm64-v8a", "armeabi-v7a"]
manifest_file = ""
intent_filters_file = "intent_filters.xml"
accept_sdk_license = "non-interactive"

[java]
jdk_version = "21"
gradle_version = "9.0.0"

[python]
python_version = "3.13.0"

[build]
type = "debug"
patches = "patches" # (write path to patches dir)
configure_arguments = "configure_arguments"


