[app]
name = "browser"
package_domain = "com.example"
version = "0.1"
main_file = "main.py"
target_platforms = ["android"]

[app.dependency]
runtime_packages = ["kivy==2.3.1", "pyjnius"]
buildtime_packages = ["libffi==3.5.2", "openssl==3.6.0"]

[app.dependency_mapping]
libffi = "https://github.com/libffi/libffi/releases/download/v{version}/libffi-{version}.tar.gz"
openssl = "https://github.com/openssl/openssl/releases/download/openssl-{version}/openssl-{version}.tar.gz"
sdl = "https://github.com/libsdl-org/SDL/releases/download/release-{version}/SDL3-{version}.tar.gz"
kivy = "https://github.com/kivy/kivy/archive/refs/tags/{version}.tar.gz"

[android]
cmdline_tools_version = "13114758"
sdk_version = "36"
ndk_version = "28.2.13676358"
min_sdk_version = "24"
ndk_api = "24"
archs = ["arm64-v8a", "armeabi-v7a"]
manifest_file = ""
intent_filters_file = "intent_filters.xml"
accept_sdk_license = "non-interactive"

[java]
jdk_version = "21"
gradle_version = "9.0.0"

[python]
python_version = "3.13.0"

[build]
type = "debug"

[build.patches]
kivy = ["kivy_android_build.patch", "gl_redirect.patch"]
